config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  get 'homes/index'
  
  root to: "users#index"
  
  get 'dashboard', to: "users#index", as: "dashboard"
  patch 'users/:id', to: "users#update", as: "update_user"

  resources :trader_stocks
  resources :orders
  resources :stocks
  
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard', to: "users#index", as: :authenticated_root
      end
    end
  end

  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'users', to: "admin_pages#index", as: :authenticated_root
        get 'users/transactions', to: "admin_pages#user_transactions"
        put 'admin_pages/approved_user', to: "admin_pages#approve_user"
        get 'add_user', to: 'admin_pages#add_user'
        post 'create_user', to: 'admin_pages#create_user'
        get 'users/:id/edit' => 'admin_pages#edit_user', as: 'edit_user'
        patch 'users/:id/edit' => 'admin_pages#update_user', as: 'update_user'
        delete 'users/:id', to: 'admin_pages#destroy', as: 'delete_user'
        get 'users/:id/view' => 'admin_pages#show_user', as: 'show_user'
      end
    end
  end
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :bigint           not null, primary key
#  balance    :decimal(15, 2)   default(0.0)
#  first_name :string
#  last_name  :string
#  username   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Portfolio < ApplicationRecord
  has_many :trader_stocks
  has_many :stocks, through: :trader_stocks
  has_many :orders
  has_many :histories
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :trader_stocks
         has_many :orders

  enum :status, { pending: 0, approved: 1 }, default: :pending

  def recalculate_balance price
    # if order_type == "BUY"
    update(balance: balance + price)
  end

  private

  def send_welcome_email
    WelcomeMailer.with(email: email).welcome_email.deliver_now
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]

  def index
    @portfolios = Portfolio.all
  end

  def show
    @client = IEX::Api::Client.new
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    if @portfolio.save
      redirect_to @portfolio
    else
      render :new
    end
  end

  def edit
  end


  def update
    if params[:commit] == "Deposit"
      result = @portfolio.balance.to_f + portfolio_params[:balance].to_f
    else
      result = @portfolio.balance.to_f - portfolio_params[:balance].to_f
    end

    if @portfolio.update(balance: result)
      redirect_to @portfolio
    end
  end



  def destroy
  end
  
  private

    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:balance, :username, :firstname, :lastname)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/histories_controller.rb
class Users::HistoriesController < ApplicationController
  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/portfolios_controller.rb
class Users::PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]

  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    if @portfolio.save
      redirect_to users_portfolios_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:commit] == "Deposit"
      result = @portfolio.balance.to_f + portfolio_params[:balance].to_f
    else
      result = @portfolio.balance.to_f - portfolio_params[:balance].to_f
    end

    if @portfolio.update(balance: result)
      redirect_to users_portfolios_path
    end
  end

  def destroy
  end
  
  private

    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:balance)
    end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_resource, except: [:new, :create]
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_resource, only: :destroy
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ update ]
  before_action :authenticate_user!

  def index
    @users = current_user
    @trader_stocks = TraderStock.where(user_id: current_user.id)
    @stocks = Stock.all
  end

  def update
    if params[:commit] == "Deposit"
      result = current_user.balance.to_f + params[:user][:balance].to_f
    else
      return if params[:user][:balance].to_f > current_user.balance.to_f
      result = current_user.balance.to_f - params[:user][:balance].to_f
    end

    if @user.update(balance: result)
      redirect_to dashboard_path
    end
  end

  private

  def set_user
    @user = User.where(id: current_user.id)
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/portfolios/_new_balance_form.html.erb
<%= form_with(url: users_update_portfolio_url(portfolio), scope: :portfolio, data: { turbo: false }, method: :patch) do |form| %>
  
  <div class = "portfolio-form">
    <%= form.number_field :balance, autocomplete: "off", value: nil, step: 0.01 %>
  </div>

  <div class="transaction-option">
    <div class="deposit-btn">
      <%= form.submit "Deposit" %>
    </div>
    <div class="withdraw-btn">
      <%= form.submit "Withdraw" %>
    </div>
  </div>

<% end %>

app/views/users/portfolios/_sidebar.html.erb
<aside id="sidebar">
  <div class="sidebar-logo">
    <h2>Stock Name App</h2>
  </div>
  <div class="sidebar-list">
    <ul>
      <h3>MENU</h3>
      <li><%= link_to "Dashboard", users_portfolios_path%></li>
      <li>My Stocks</li>
      <li><%= link_to "Stocks List", users_stocks_path %></li>
      <li><%= link_to "History", users_histories_path %></li>
      <li>Settings</li>
    </ul>
    <ul>
      <h3>SUPPORT</h3>
      <li>Contact Us</li>
      <li>Community</li>
    </ul>
  </div>
</aside>

app/views/users/portfolios/index.html.erb
<%= render "/shared/navbar" %>
<div id="portfolio-container">
  <%= render "sidebar"%>
  <div class="portfolio-content">
    <%= render "header"%>
    <main class="portfolio-dashboard">
      <figure class="grid-1">1</figure>
      <figure class="grid-2">
        <div class="trade-stock">
          <select name="stock-name" id="stock-name-dd">
            <option value="" disabled selected hidden>Select Stock</option>
            <option value="TSLA">Tesla Inc</option>
            <option value="AAPL">Apple Inc</option>
            <option value="AMZN">Amazon.com Inc.</option>
          </select>
          <div>
            <%# <input type="number"/> %>
            <h2>10</h2>
            <h3>X</h3>
            <h2>$119.77</h2>
          </div>
          <h2>TOTAL PRICE: $1197.70</h2>
        </div>
        <div class="trade-stock-type">
          <button>BUY</button>
          <button>SELL</button>
        </div>
      </figure>
      <figure class="grid-3">3</figure>
      <figure class="grid-4">4</figure>
      <figure class="grid-5">5</figure>
      <figure class="grid-6">6</figure>
      <figure class="grid-7">
        <div class="balance">
          <h3>Wallet Balance</h3>
          <h1><%= number_to_currency(@portfolios.first.balance, :unit => "$") %></h1>
        </div>
        <div class="change-balance">
          <%= render "new_balance_form", portfolio: @portfolios.first %>
        </div>
      </figure>
    </main>
  </div>
</div>